
name: Docker BuildKit Cache 

on:
    push:
        branches:
            - main
    pull_request:
    
jobs:
    build-image:
        name: Building Image
        runs-on: Ubuntu-latest
        steps:

            - name: Setting up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}


            - name: Docker build
              uses: docker/build-push-action@v6
              with: 
                push: ${{ github.event_name != 'pull-request' }}
                tags: wvrmhat/httpenv:latest,wvrmhat/httpenv:02

                cache-from: type = gha
                cache-to: type = gha, mode = max


                

        




