
name: Multiplatform build including Metadata 

on:
    push:
        branches:
            - main
    pull_request:
    
jobs:
    build-image:
        name: Building Image
        runs-on: Ubuntu-latest
        steps:

            - name: Setting up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setting up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            # step before building to add tags and metadata 
            - name: Metadata and Dynamic tags
              id: docker_metadata
              uses: docker/metadata-action@v5
              with:
                images: wvrmhat/httpenv
                flavor: |
                    latest=false
                tags: |
                    type=raw,value=04
                    type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
                    type=ref,event=pr
                    type=ref,event=branch
                    type=semver,pattern={{version}} 
              
            
            - name: Docker build
              uses: docker/build-push-action@v6
              with: 
                push: true
                tags: ${{ steps.docker_metadata.outputs.tags }}
                labels: ${{ steps.docker_metadata.outputs.tags }}
                cache-from: type=gha
                cache-to: type=gha, mode=max

                platforms: linux/amd64,linux/arm64,linux/arm/v7


                

        




